/**
 * Internal error codes for observability and client-side handling.
 *
 * Format: DOMAIN_REASON (e.g. AUTH_INVALID_CREDENTIALS)
 * - 4xx codes map to client errors (validation, auth, not found)
 * - 5xx codes map to server/external failures
 */
export enum ErrorCode {
  // Generic
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  RATE_LIMITED = 'RATE_LIMITED',

  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_REVOKED = 'AUTH_REFRESH_REVOKED',

  // Trading / signals
  SIGNAL_NOT_FOUND = 'SIGNAL_NOT_FOUND',
  SIGNAL_EXPIRED = 'SIGNAL_EXPIRED',
  POSITION_NOT_FOUND = 'POSITION_NOT_FOUND',
  POSITION_INVALID_CLOSE = 'POSITION_INVALID_CLOSE',
  RISK_LIMIT_EXCEEDED = 'RISK_LIMIT_EXCEEDED',

  // External sources / engine
  EXTERNAL_API_ERROR = 'EXTERNAL_API_ERROR',
  ENGINE_UNAVAILABLE = 'ENGINE_UNAVAILABLE',
  CIRCUIT_BREAKER_OPEN = 'CIRCUIT_BREAKER_OPEN',

  // Billing / limits
  PLAN_LIMIT_REACHED = 'PLAN_LIMIT_REACHED',
  SUBSCRIPTION_INACTIVE = 'SUBSCRIPTION_INACTIVE',
}

export const HTTP_STATUS_BY_CODE: Record<ErrorCode, number> = {
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.RATE_LIMITED]: 429,

  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCode.AUTH_TOKEN_INVALID]: 401,
  [ErrorCode.AUTH_REFRESH_REVOKED]: 401,

  [ErrorCode.SIGNAL_NOT_FOUND]: 404,
  [ErrorCode.SIGNAL_EXPIRED]: 400,
  [ErrorCode.POSITION_NOT_FOUND]: 404,
  [ErrorCode.POSITION_INVALID_CLOSE]: 400,
  [ErrorCode.RISK_LIMIT_EXCEEDED]: 400,

  [ErrorCode.EXTERNAL_API_ERROR]: 502,
  [ErrorCode.ENGINE_UNAVAILABLE]: 503,
  [ErrorCode.CIRCUIT_BREAKER_OPEN]: 503,

  [ErrorCode.PLAN_LIMIT_REACHED]: 403,
  [ErrorCode.SUBSCRIPTION_INACTIVE]: 403,
};
